langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install: raco pkg install --deps search-auto $TRAVIS_BUILD_DIR/ipoe

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - echo "#:user \"postgres\"\n#:dbname \"travis_ci_test\"" > $HOME/.ipoe

script:
  - raco test $TRAVIS_BUILD_DIR/ipoe

after_success:
  - raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage $TRAVIS_BUILD_DIR/ipoe/private
